### ISSUE TITLE
EPIC: Introduce integration and end-to-end tests

### ISSUE THREAD

**Issue by andrewpengucsb** [ucsb-cs156/proj-gauchoride#102]
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

developer

### I can...

run integration and end-to-end tests

### So that...

my test suite is more comprehensive

### Discussion

Right now the test suite contains only unit tests. 

We want to add integration tests and end-to-end tests slowly into the application.

This epic involves adding all of the necessary setup to allow for the addition of integration and end-to-end tests.

This guide [Going Beyond Unit Tests](https://ucsb-cs156.github.io/topics/spring_react/spring_react_testing_pyramid.html) covers every step of the process in detail. Please follow it and adapt as necessary since the guide was based on proj-happycows. 

### Acceptance Criteria

- [ ] Developer can use a series of commands specified in the guide to run the integration and end-to-end test suite.

### Implementation Todos

Issue 1 :  (Step 1 and 2 in the guide)
- [ ] Modify `pom.xml` with the necessary dependencies and new Maven profiles
- [ ] Add some `.properties` files for the new Spring profiles

Issue 2 : Wiremock Service (Step 3)
- [ ] Add the WiremockService and related files
- [ ] Make all necessary changes to the rest of the code to support it

Issue 3 : New github workflow (Step 6 and 7)
- [ ] Add a new github workflow that runs the (currently empty) integration and end-to-end test suite
- [ ] Document the testing flow in the readme

Issue 4 : Integration tests (Step 4)
- [ ] Add an integration test for something of your choice

Issue 5 : End-to-end test (Step 5)
- [ ] Add an end-to-end test for something of your choice
