### ISSUE TITLE
EPIC: Driver Dashboard page

### ISSUE THREAD

**Issue by bzamora020** [ucsb-cs156/proj-gauchoride#48]
# User Story

* As a driver
* I can see a tab on the navbar for Driver that takes me to a Driver dashboard page
* so that the most relevant information for me as a driver is easy to find

# Discussion

If a user is a driver, there should be a driver button (which might become a Driver menu later, but a button is fine for now) that brings up a Driver page.

On that driver page, there should be a list of:
* All of the shifts that a driver is assigned to
* All of the rides that driver is assigned to

### First issue: establish placeholder for driver page

- [ ] As a driver, I can see in the navbar a link where I can navigate to a "drivers" page
- [ ] There is a respective route for this page `/driver`
- [ ] A page loads when the driver navigates to the `/driver` page (could be a placeholder page at first.)

### Second issue: add table of driver shifts

- [ ] As a driver, a list of all of my shifts on the `/driver` page

### Third issue: add table of ride requests to which I am assigned

Note that until we build the functionality to assign drivers to rides, this will not make sense, so you may need to wait on this part.

- [ ] As a driver, a list of all the rides to which I am assigned as the driver is shown on the `/driver` page.

**Comment by Mohamed-Elfouly** [comment]
None of this was done in m23 so I will leave it as a feature to be done by the f23 class
