### ISSUE TITLE
EPIC: Adjust Ride Request fields to clarify pickup and dropoff

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-gauchoride#61]
# User Story

* As a rider / driver
* I can be clear about the pick up and dropoff locations
* So that there is no confusion when picking up and dropping off riders

### Discussion

Currently, this is what the table of ride requests looks like:

<img width="1349" alt="image" src="https://github.com/ucsb-cs156/proj-gauchoride/assets/1119017/6fdf576c-f1ed-40be-a9d9-dea967e16ab2">

The original spreadsheet looked like this:

<img width="1063" alt="image" src="https://github.com/ucsb-cs156/proj-gauchoride/assets/1119017/6a704aea-491d-4eba-bbed-bb479b5ba153">

What we want to do is clarify things by having four fields: 
* Pick up Building
* Pick up Room
* Drop off Building
* Drop off Room

The room should be an optional field, since sometimes it is not applicable.   But the building should be required.

We should also add a "notes" field that is free form text and optional but a place where any extra information can be noted.

This will require involve multiple frontend  and backend stories, and should be broken up into multiple issues/PRs.

### Acceptance Criteria

- [ ] Where there were three fields (`Pick Up`,  `Drop Off`,  `Room #`), there are now five fields:  (`Pick Up Building`, `Pick Up Room #` `Drop Off Building`,  `Drop Off Room #`, `Notes`) on the `/ride` page
- [ ] Same set of changes on the  `ride/create` page 
- [ ] Same set of changes on the `/ride/edit/:rideId` page

### Implementation Todos

Suggest breaking up into multiple issues/PRs:

###  First issue: rename fields and add new fields

In the first issue/PR, we just make changes in the backend to prepare for the new fields.

- [ ] Rename `room;` in `Ride` entity to `dropoffRoom`
- [ ] Add `pickupRoom` and `notes` to  `Ride` entity.
- [ ] Adjust controller endpoints for POST, PUT for renaming of `room` to `dropoffRoom` and to include code for the two new fields
- [ ] Make the smallest number of changes to possible to the frontend in the first PR so that everything still works; that is, in this first PR, the frontend *will still look exactly the same*.  Ideally, the only change is to change the name of the `room` field to `dropoffRoom` inside the code the interfaces with the backend.

At this first stage, it is fine that there is no way yet to access `pickupRoom` and `notes` in the frontend.  Since those fields are optional, it is not a problem that they are not being set (or they can be set to empty string for now.  We'll add those in the next issue/PR.

###  Second issue: adjust frontend for new fields

In the next PR, we take the fields that are now present in the backend, and expose them in the frontend.

- [ ] Add the three new fields, and change name of the other two in `frontend/src/main/components/Ride/RideForm.js` and fix tests
- [ ] Add the three new fields, and change name of the other two in `frontend/src/main/components/Ride/RideTable.js` and fix tests
- [ ] Adjust`RideRequestCreatePage.js`, `RideRequestEditPage.js`, `RideRequestIndexPage.js` and associated tests for the new fields.

**Comment by pconrad** [comment]
This issue is worth at least 20 points.   As it is a priority issue, if a team fails to complete it, up to 20 points may be deducted from the project grade for that team.
