### ISSUE TITLE
EPIC: Any user can add their cell phone 

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-gauchoride#62]
# User Story 

* As a user
* I can add my cell phone
* So that drivers / riders can communicate with one another

### Discussion

The current spreadsheet provided by Mike Fogelsonger has a list of cell phone numbers for drivers.  This is used by the drivers to communicate with one another.

Similarly, it is helpful for drivers and riders to have each other's cell phone numbers.

In this issue, we make it possible (but not required) for any user to provide their cell phone number, and have that associated with their record in the Users table.

### Acceptance Criteria

# First Issue: add cell to user entity

- [ ] The user entity has a field for cell phone number (String)

# Second issue: allow updating of cell phone in backend

- [ ] There is a new UserProfileController that has a route `PUT /api/userprofile` that takes a single parameter `cellPhone` of type string.  If there is a logged in user, it updates the cell phone number for that logged in user; otherwise it returns a 403.

# Third issue: display cell phone on user profile page

- [ ] On the `/profile` page (i.e. in the `frontend/src/main/pages/ProfilePage.js` component) the cell phone number is displayed.

# Fourth issue: There is a way to update the cell phone 

- [ ] On the `/profile` page (i.e. in the `frontend/src/main/pages/ProfilePage.js` component) next to the cell phone number, there is a button that takes the user either to a Modal (see: https://react-bootstrap.netlify.app/docs/components/modal/ ) or a new page (implementer's choice) where they can update the cell phone number.  If it's a new page, on updating the user is redirected back to the profile page.

**Comment by pconrad** [comment]
This Epic is worth at least 20 points. As it is a priority issue, if a team fails to complete it, up to 20 points may be deducted from the project grade for that team.

**Comment by pconrad** [comment]
Closed by #69
