### ISSUE TITLE
FEATURE EPIC: Rider dashboard page

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-gauchoride#64]
# User Story

* As a rider
* I can see a tab on the navbar for Rider that takes me to a Rider dashboard page
* so that the most relevant information for me as a rider is easy to find

# Discussion

If a user is a rider, there should be a rider button (which might become a Rider menu later, but a button is fine for now) that brings up a Rider dashboard page.

On that rider page, there should be a list of:
* All of the rides that the rider has requested

### First issue: establish placeholder for driver page

- [ ] As a rider, I can see in the navbar a link where I can navigate to a "rider" page
- [ ] There is a respective route for this page `/rider`
- [ ] A page loads when the rider navigates to the `/rider` page (could be a placeholder page at first.)

### Second issue: add table of ride requests

- [ ] As a rider, a list of all of my ride requests on the `/rider` page

**Comment by Mohamed-Elfouly** [comment]
None of this was done, there was an attempt by m23-9am-2 but it was never merged. I will leave this as a feature for the f23 class
