### ISSUE TITLE
EPIC: Admins can assign drivers to rides

### ISSUE THREAD

**Issue by andrewpengucsb** [ucsb-cs156/proj-gauchoride#95]
### As a...

Admin

### I can...

Assign drivers to ride requests

### So that...

drivers can know which ride requests they need to fulfill

### Discussion

Right now ride requests have a field for drivers:
![image](https://github.com/ucsb-cs156/proj-gauchoride/assets/56096744/ec5cb3dc-b94f-473a-98ac-7e72b0c0b347)

Currently there is no way to add a driver to the ride request despite the field being in the table, and no way to show drivers which ride requests they should fulfill during a shift.
![image](https://github.com/ucsb-cs156/proj-gauchoride/assets/56096744/93984b29-9bca-4f7b-8b69-6c0e7eb9b534)

These todos will be rough in order to just get this epic out there, if you would like more clarification on the acceptance criteria or implementation todos reach out to Andrew P during lecture or discussion

### Admin Perspective
- [ ] When an admin is viewing all of the ride requests, there should be a button in the table that only shows up for admins `Assign Driver` which takes the admin to `/ride/assigndriver/`
- [ ] On this page it will show information about the ride request, including a drop down menu that lists only the drivers whose shift matches with the period of the ride request. This can initially be a text field where the admin can input a number.
- [ ] Instead of a `Driver` column in the frontend table, there should be a `Shift` column that shows the shift number, which is a hyperlink to a Shift Info page which displays information about the Shift and a table of Ride Requests associated with it.
- [ ] When looking at the table of shifts, there should be a button that links to the same info page.

### Driver Perspective

- [ ] Can see and click the button on the list of shifts that links to the info page.

### Implementation Todos

BACKEND

Add field to backend RideRequest, called `shiftId` that is automatically assigned to some stub value ( like 0 ) on RideRequest creation.
Admin can fill in this value with a backend endpoint.
Endpoint for driver and admin that gets all the Ride Requests associated with a given shiftId

FRONTEND

Fulfill above acceptance criteria
